---
- name: Install apt packages
  apt:
    name: "{{ systemd_service_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 86400

# Service file
- name: Create service file for {{ systemd_service_name }}
  when: systemd_service_content or systemd_service_file or systemd_service_template
  notify: Restart systemd service {{ systemd_service_name }}
  block:
    - name: Make service file with content
      when: systemd_service_content
      copy:
        content: "{{ systemd_service_content }}"
        dest: /etc/systemd/system/{{ systemd_service_name }}.service
        mode: "0644"
        owner: root
        group: root

    - name: Create service file from template file
      when: systemd_service_template
      template:
        src: "{{ systemd_service_template }}"
        dest: /etc/systemd/system/{{ systemd_service_name }}.service
        mode: "0644"
        owner: root
        group: root

    - name: Copy service file
      when: systemd_service_file
      copy:
        src: "{{ systemd_service_file }}"
        dest: /etc/systemd/system/{{ systemd_service_name }}.service
        mode: "0644"
        owner: root

- name: Create service file with default template
  when:
    - systemd_service_use_template_default
    - not (systemd_service_content or systemd_service_file or systemd_service_template)
    - not (systemd_service_docker_compose_files or systemd_service_docker_compose_templates)
  copy:
    content: "{{ systemd_service_template_default }}"
    dest: /etc/systemd/system/{{ systemd_service_name }}.service
    mode: "0644"
    owner: root
    group: root
  notify: Restart systemd service {{ systemd_service_name }}

# Timer file
- name: Create timer file for {{ systemd_service_name }}
  when: systemd_service_timer_content or systemd_service_timer_file or systemd_service_timer_template
  notify: Restart systemd timer {{ systemd_service_name }}
  block:
    - name: Make timer file with content
      when: systemd_service_timer_content
      copy:
        content: "{{ systemd_service_timer_content }}"
        dest: /etc/systemd/system/{{ systemd_service_name }}.timer
        mode: "0644"
        owner: root
        group: root

    - name: Create timer file from template file
      when: systemd_service_timer_template
      template:
        src: "{{ systemd_service_timer_template }}"
        dest: /etc/systemd/system/{{ systemd_service_name }}.timer
        mode: "0644"
        owner: root
        group: root

    - name: Copy timer file
      when: systemd_service_timer_file
      copy:
        src: "{{ systemd_service_timer_file }}"
        dest: /etc/systemd/system/{{ systemd_service_name }}.timer
        mode: "0644"
        owner: root
        group: root

    - name: Ensure timer is activated
      systemd:
        name: "{{ systemd_service_name }}.timer"
        enabled: true

# Directories
- name: Create directories
  file:
    path: "{{ item.path | default(item) }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  loop: "{{ systemd_service_dirs }}"

- name: Check directories
  stat:
    path: "{{ item.dest | dirname }}"
  loop: "{{ systemd_service_templates + systemd_service_files }}"
  register: dir_stat

- name: Create missing directories only
  file:
    path: "{{ item.item.dest | dirname }}"
    state: directory
    mode: "0755"
    owner: "{{ item.item.owner | default(omit) }}"
    group: "{{ item.item.group | default(omit) }}"
  loop: "{{ dir_stat.results }}"
  when:
    - systemd_service_auto_create_dirs
    - not item.stat.exists

# Files
- name: Make files from templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  loop: "{{ systemd_service_templates }}"
  notify: Restart systemd service {{ systemd_service_name }}

- name: Copy local files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  loop: "{{ systemd_service_files }}"
  when: item.src is not match('^[a-zA-Z][a-zA-Z0-9+.-]*://')
  notify: Restart systemd service {{ systemd_service_name }}

- name: Download remote files
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  loop: "{{ systemd_service_files }}"
  when: item.src is match('^[a-zA-Z][a-zA-Z0-9+.-]*://')
  notify: Restart systemd service {{ systemd_service_name }}

# Docker
- name: Prepare for docker
  when: systemd_service_docker_compose_files or systemd_service_docker_compose_templates
  notify: Restart systemd service {{ systemd_service_name }}
  block:
    - name: Create docker base dir
      file:
        path: "{{ systemd_service_docker_base_dir }}"
        state: directory
        mode: "0755"
        owner: root
        group: root

    # Docker compose files
    - name: Create docker compose file from content
      copy:
        dest: "{{ systemd_service_docker_base_dir }}/{{ systemd_service_name }}/docker-compose.yml"
        mode: "0644"
        owner: root
        group: root
        content: "{{ systemd_service_docker_compose_content }}"
      when: systemd_service_docker_compose_content

    - name: Create docker compose files from templates
      template:
        src: "{{ item }}"
        dest: "{{ systemd_service_docker_base_dir }}/{{ systemd_service_name }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
        mode: "0644"
        owner: root
        group: root
      loop: "{{ systemd_service_docker_compose_templates }}"
      when: not systemd_service_docker_compose_content

    - name: Copy local docker compose files
      copy:
        src: "{{ item }}"
        dest: "{{ systemd_service_docker_base_dir }}/{{ systemd_service_name }}/{{ item | basename }}"
        mode: "0644"
        owner: root
        group: root
      loop: "{{ systemd_service_docker_compose_files }}"
      when:
        - not systemd_service_docker_compose_content
        - item is not match('^[a-zA-Z][a-zA-Z0-9+.-]*://')

    - name: Download remote docker compose files
      get_url:
        url: "{{ item }}"
        dest: "{{ systemd_service_docker_base_dir }}/{{ systemd_service_name }}/{{ item | basename }}"
        mode: "0644"
        owner: root
        group: root
      loop: "{{ systemd_service_docker_compose_files }}"
      when:
        - not systemd_service_docker_compose_content
        - item is match('^[a-zA-Z][a-zA-Z0-9+.-]*://')

    # Docker compose env file
    - name: Create docker env file from content
      copy:
        dest: "{{ systemd_service_docker_base_dir }}/{{ systemd_service_name }}/.env"
        mode: "0640"
        owner: root
        group: root
        content: "{{ systemd_service_docker_compose_env_content }}"
      when: systemd_service_docker_compose_env_content

    - name: Create docker compose env file from template
      template:
        src: "{{ systemd_service_docker_compose_env_template }}"
        dest: "{{ systemd_service_docker_base_dir }}/{{ systemd_service_name }}/.env"
        mode: "0640"
        owner: root
        group: root
      when: not systemd_service_docker_compose_env_content

    - name: Copy local docker compose env file
      copy:
        src: "{{ systemd_service_docker_compose_env_file }}"
        dest: "{{ systemd_service_docker_base_dir }}/{{ systemd_service_name }}/.env"
        mode: "0640"
        owner: root
        group: root
      when:
        - systemd_service_docker_compose_env_file
        - not systemd_service_docker_compose_env_content
        - systemd_service_docker_compose_env_file is not match('^[a-zA-Z][a-zA-Z0-9+.-]*://')

    - name: Download remote docker compose env file
      get_url:
        url: "{{ systemd_service_docker_compose_env_file }}"
        dest: "{{ systemd_service_docker_base_dir }}/{{ systemd_service_name }}/.env"
        mode: "0640"
        owner: root
        group: root
      when:
        - systemd_service_docker_compose_env_file
        - not systemd_service_docker_compose_content
        - systemd_service_docker_compose_env_file is match('^[a-zA-Z][a-zA-Z0-9+.-]*://')

    # Docker volume dirs
    - name: Docker volume dirs
      file:
        path: "{{ (systemd_service_docker_volume_base_dir, item.path) | path_join }}"
        state: directory
        mode: "{{ item.mode | default('0755') }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
      loop: "{{ systemd_service_docker_compose_volume_dirs }}"

    # Docker systemd service file
    - name: Make systemd service file for docker project
      copy:
        content: "{{ systemd_service_docker_service_template_default }}"
        mode: "0644"
        dest: /etc/systemd/system/{{ systemd_service_name }}.service
      when:
        - not systemd_service_content
        - not systemd_service_file
        - not systemd_service_template


- name: Enable and start service
  systemd:
    name: "{{ systemd_service_name }}"
    enabled: true
    state: started
