- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Restart systemd service {{ systemd_service_name }}
  systemd:
    name: "{{ systemd_service_name }}"
    daemon_reload: true
    state: restarted
  when:
    - not systemd_service_timer_file
    - not systemd_service_timer_content
    - not systemd_service_timer_template

- name: Restart systemd timer {{ systemd_service_name }}
  systemd:
    name: "{{ systemd_service_name }}.timer"
    daemon_reload: true
    state: restarted
    enabled: true
