- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Restart systemd service {{ systemd_service_name }}
  systemd:
    name: "{{ systemd_service_name }}"
    daemon_reload: true
    state: restarted

- name: Restart systemd timer {{ systemd_service_name }}
  systemd:
    name: "{{ systemd_service_name }}.timer"
    daemon_reload: true
    state: restarted
